config/routes.rb
Rails.application.routes.draw do
  
  resources :contests
  resources :teams
  resources :posts
  get 'home/index'
  root 'home#index'
  
  get 'home/diet_program'

  devise_for :users
  
  post '/posts/:post_id' =>"comments#create"
  delete '/posts/:post_id/comments/:id' =>"comments#destroy"
  post '/posts/:post_id/comments/:id' =>"comments#update"
  post '/tinymce_assets' => 'tinymce_assets#create'
  

  
  get '/suzy' => "home#suzy"
  get '/sulhyun' => "home#sulhyun"
  get '/iu' => "home#iu"
  get '/dongwon' => "home#dongwon"
  get '/contact' => "home#contact"
  post '/home/contact' => 'home#contact'
  
  get '/zzim' => "home#zzim"
  get 'home/delete'
  get 'home/delete/:id' => 'home#delete'

  

end

app/models/contest.rb
class Contest < ActiveRecord::Base
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]

  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(contest_params)

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.fetch(:contest, {})
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing Contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= link_to 'Show', contest %></td>
        <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
        <td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contest', new_contest_path %>

app/views/contests/new.html.erb
<h1>New Contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contest_path(@contest) %> |
<%= link_to 'Back', contests_path %>