config/routes.rb
Rails.application.routes.draw do
  
  resources :contests
  resources :teams
  resources :posts
  get 'home/index'
  root 'home#index'
  
  get 'home/diet_program'

  devise_for :users
  
  post '/posts/:post_id' =>"comments#create"
  delete '/posts/:post_id/comments/:id' =>"comments#destroy"
  post '/posts/:post_id/comments/:id' =>"comments#update"
  post '/tinymce_assets' => 'tinymce_assets#create'
  

  
  get '/suzy' => "home#suzy"
  get '/sulhyun' => "home#sulhyun"
  get '/iu' => "home#iu"
  get '/dongwon' => "home#dongwon"
  get '/contact' => "home#contact"
  post '/home/contact' => 'home#contact'
  
  get '/zzim' => "home#zzim"
  get 'home/delete'
  get 'home/delete/:id' => 'home#delete'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%=tinymce%>
    <%= f.text_area :content, :class => "form-control tinymce", :rows => 40, :cols => 120 %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <h1>게시판 목록</h1>
  
  <table class="table">
    <thead>
      <tr>
        <th>제목</th>
        <th>작성자</th>
        <th>작성시간</th>
      </tr>
    </thead>
  
    <tbody>
      <% @postss =@posts.reverse %>
      <% @postss.each do |post| %>
        <tr>
          <td><%= link_to post.title , post %></td>
          <td><%= post.user.name %></td>
          <td><%= post.created_at.in_time_zone("Asia/Seoul").strftime("%Y년%m월%d일 %H시%M분") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to '새글작성', new_post_path %>
  <p><a href="/">홈페이지로</a></p>

</div>

app/views/posts/new.html.erb
<div class="container">
    <h1>새글작성</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
  
  <h2><%= @post.title %></h2>
  <hr>
  <p><strong>작성자 : <%= @post.user.name %></strong></p>
  <hr>
  <p><strong>작성시간 : <%=@post.created_at.in_time_zone("Asia/Seoul").strftime("%Y년%m월%d일 %H시%M분")%></strong></p>
  <hr>
  <p><strong>내용</strong></p>
  <p><%= @post.content.html_safe%></p>
  
  <hr>
  <% if can? :update, @post %>
      <%= link_to 'Edit', edit_post_path(@post) %> |
  <% end %>
  <% if can? :delete, @post %>
      <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %> | 
  <% end %>
  <%= link_to '목록으로', posts_path %> 

  
  
  
  <hr>
  <p><strong>댓글목록</strong></p>
  <% @comments = @post.comments.all %>
  <% @comments.each do |c| %>
  <div class="well">
  <p class="original-comment" id="<%=c.id %>">작성자 : <%= c.user.email %></p>
  <p class="original-comment" id="<%=c.id %>">작성시간 : <%= c.created_at.in_time_zone("Asia/Seoul").strftime("%Y년%m월%d일 %H시%M분") %></p>
  <p class="original-comment" id="<%=c.id %>">내용 : <%= c.comment %></p>
  <div class="edit-comment-<%=c.id%>" style="display:none;">
    <form action="/posts/<%=@post.id%>/comments/<%=c.id%>" method="post">
      <div class="form-group">
        <input type="hidden" value="<%=current_user.id%>" name="user_id"></input>
        <input type="hidden" value="<%=@post.id%>" name="post_id"></input>
        <textarea class="form-control" rows="5" name="comment"><%=c.comment %></textarea>
      </div>
      <button type="submit" class="btn btn-default">수정완료!</button>
    </form>
    </br>
  </div>
  <div class="edit-comment-<%=c.id%>-button-group">
    <% if can? :update, c %>
    <button class="btn btn-default edit-button" id="edit-comment-<%=c.id %>">수정</button>
    <%end%>
    
    <% if can? :delete, c %>
    <a href="/posts/<%=@post.id%>/comments/<%=c.id%>" data-method="delete" class="btn btn-default">삭제</a>
    <%end%>
  </div>
  </div>
  <% end %>

  <p><strong>댓글작성</strong></p>
  <div class="well">
    <form action="/posts/<%=@post.id%>" method="post">
      <div class="form-group">
        <input type="hidden" value="<%=current_user.id%>" name="user_id"></input>
        <input type="hidden" value="<%=@post.id%>" name="post_id"></input>
        <textarea class="form-control" rows="5" name="comment"></textarea>
      </div>
      <button type="submit" class="btn btn-default">댓글작성!</button>
    </form>
  </div>
  <hr>

</div>



<script>
  $(".edit-button").click(function() {
    var clickedID = this.id;
    $("."+clickedID).css("display","block");
    $("."+clickedID+"-button-group").css("display","none");
  });
  
</script>